name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"] # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Or your preferred Node.js version
          cache: "npm" # Or yarn, pnpm
      - name: Install dependencies
        run: npm install # Or yarn install, pnpm install
      - name: List files before build # DEBUG STEP
        run: ls -R .
      - name: Build with Next.js
        run: npm run build # Or yarn build, pnpm build
      - name: Check build command exit code # DEBUG STEP
        run: echo "Build command exit code: $?"
      - name: List files after build to check for 'out' directory # DEBUG STEP
        run: ls -R .
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
