name: Build and Deploy Next.js to gh-pages (zerofail)

on:
  push:
    branches:
      - main # Or your primary development branch
  workflow_dispatch:

permissions:
  contents: write # Needed to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        # This runs `next build` and `next export` (due to output: 'export' in next.config.ts)
        # The output will be in the 'out' directory.
        run: npm run build

      - name: Add .nojekyll file to out directory
        run: touch ./out/.nojekyll
        # This file tells GitHub Pages to not run the static site files through Jekyll,
        # which is important for Next.js sites with folders starting with underscores (like _next).

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3 # Action to deploy to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # The directory to publish (your Next.js build output)
          # user_name: 'github-actions[bot]' # Optional: Custom committer name
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: Custom committer email
          # cname: your.custom.domain # Optional: if you have a custom domain
          # publish_branch: gh-pages # This is the default, but can be explicit
